plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Lint/ConstantDefinitionInBlock:
  Exclude:
    - lib/bp3/**/railtie.rb

Lint/Void:
  Exclude:
    - lib/bp3/**/railtie.rb

Metrics/AbcSize:
  Max: 26

Metrics/BlockLength:
  Max: 66

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 10

Naming/FileName:
  Exclude:
    - lib/bp3-*.rb

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 4

Style/Documentation:
  Enabled: false
