require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/AbcSize:
  Max: 26

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 10

Naming/FileName:
  Exclude:
    - lib/bp3-*.rb

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 4

Style/Documentation:
  Enabled: false
